### ISSUE TITLE
crypto token

### ISSUE THREAD

**Issue by dnapier** [vadimpronin/guacamole-lite#22]
I'm a bit confused regarding the use of the token.

I'm passing a json token to the guacamole-lite server listening at port 8080 from the client side javascript using guacamole-common-js.

It needs to be encrypted with the crypto package but the crypto package is only available on node (server side).  The crypto example you gave is for encrypting the token to send to the guacamole-lite server, correct? 

What am I missing here?

**Comment by vadimpronin** [comment]
Ok, the token is basically one of the ways to tell guacamole-lite to which server it should connect and with what parameters. Because the token is just an encrypted json with all these parameters.
Now there are multiple ways to send these parameters to guacamole-lite:
1. Encrypted token
2. Unencrypted GET parameters (query string)
3. Hardcoded config in guacamole-lite

I don't really understand what is your use case, but from your question I assume that you want to configure connection parameters (IP, login, password, etc) on the frontend (in browser). If that is true, I must warn you that though it is possible (by overriding some guacamole-lite defaults) it is very unsecure because first of all anyone would be able to use you guacamole-lite instance to connect to any server server they want (not only the ones you want them to) and also anyone would be able to see all credentials needed to connect to your servers (IP, login, password, etc). So generally it is a very bad idea to generate connection parameters (either in token on unencrypted) on the frontend.

The idea behind the token is that your backend app takes connection parameters, encrypts them into the token and then passes this token to the frontend. In this case a user will not be able to decrypt it and see you connection parameters. And also as long as the token is generated using a key that is only known to your backend app and guacamole-lite we ensure that a user can not generate the token with their own connection parameters and try to connect to some random server.

And that is the reason why both examples of generating the token are for the backend (nodejs and PHP) and you probably can't (or at least you should not) generate tokens in browser.

**Comment by dnapier** [comment]
Update on this, after reading through the implementation for WebSocketTunnel, we found that everything following the domain:port needed to be passed to client.connect(token), rather than the above code.  I plan to update your documentation with a front end example, to clarify for others running into these issues.  This issue can be closed. :+1:

**Comment by BartNetJS** [comment]
Hi @dnapier, where can I find your front end example?
I'm struggling with the same issue on encrypting a token client side

**Comment by dnapier** [comment]
Hey @BartNetJS! Sorry, I never got around to putting in a pull request for this. I'll try to get it in later today, but just as a heads up, our implementation uses React, and while this issue got resolved, we still have an issue of user input. Currently it loads the remote connection but we haven't been able to interact with it.

**Comment by dnapier** [comment]
@BartNetJS: Fresh off the press, just created this pull request. Let me know if you have any questions regarding it!

https://github.com/vadimpronin/guacamole-lite/pull/25

**Comment by BartNetJS** [comment]
great @dnapier, i will test it tomorrow and let you know

**Comment by vadimpronin** [comment]
@dnapier Thanks for the example!
@BartNetJS please let me know the results of your test so I could merge the pull request

**Comment by BartNetJS** [comment]
@dnapier it is working great. thanks!
@vadimpronin I didn't test the react implementation. I've just copied parts of the code. So I can only confirm that the connection to guacamole-lite works.
